# Training Settings
num_workers : 8
num_epochs : 50
batch_size : 16
init_lr_rate : 3.0e-4

# Device Settings
device : 1
use_fp16 : True

# Task Settings
task : MRNET_KNEE_3B
num_cls : 4
pretrain : None

# Test Mode
test : False